cloud:
  aws:
    credentials:
      access-key: put-your-access-key
      secret-key: put-your-secret-key
    region:
      static: us-east-1
    stack:
      auto: false

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090